## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [15]:
# Determine the number of unique values in each column.

application_cat = application_df.columns.tolist()
application_df[application_cat].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [16]:
# Look at APPLICATION_TYPE value counts for binning
app_type_value_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_value_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [20]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [29]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_value_counts[app_type_value_counts > 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

Other    34023
T9         156
T13         66
T12         27
T2          16
T25          3
T14          3
T29          2
T15          2
T17          1
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Look at CLASSIFICATION value counts for binning
call_type_value_counts = application_df['CLASSIFICATION'].value_counts()
call_type_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [31]:
# You may find it helpful to look at CLASSIFICATION value counts >1
call_type_value_counts[call_type_value_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [32]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(call_type_value_counts[call_type_value_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [34]:
# Convert categorical data to numeric with `pd.get_dummies`
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [38]:
# Split our preprocessed data into our features and target arrays
X = application_with_dummies_df.drop(['IS_SUCCESSFUL'], axis='columns').values
y = application_with_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [41]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [50]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  15
hidden_nodes_layer2 = 10
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 15)                675

 dense_14 (Dense)            (None, 10)                160

 dense_15 (Dense)            (None, 10)                110

 dense_16 (Dense)            (None, 1)                 11

=================================================================
Total params: 956
Trainable params: 956
Non-trainable params: 0
_________________________________________________________________

In [51]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [52]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6091 - accuracy: 0.6855
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5830 - accuracy: 0.7048
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5790 - accuracy: 0.7071
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5775 - accuracy: 0.7086
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5766 - accuracy: 0.7086
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5757 - accuracy: 0.7082
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5752 - accuracy: 0.7112
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5744 - accuracy: 0.7107
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5738 - accuracy: 0.7120
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5735 - accuracy: 0.7113
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5736 - accuracy: 0.7121
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5732 - accuracy: 0.7118
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5730 - accuracy: 0.7110
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5728 - accuracy: 0.7124
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5727 - accuracy: 0.7125
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5725 - accuracy: 0.7142
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5723 - accuracy: 0.7123
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5724 - accuracy: 0.7140
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5720 - accuracy: 0.7128
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5716 - accuracy: 0.7127
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5718 - accuracy: 0.7141
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5718 - accuracy: 0.7124
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5715 - accuracy: 0.7126
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5716 - accuracy: 0.7135
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5715 - accuracy: 0.7147
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5714 - accuracy: 0.7139
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5712 - accuracy: 0.7134
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5712 - accuracy: 0.7153
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5712 - accuracy: 0.7128
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5713 - accuracy: 0.7135
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5708 - accuracy: 0.7147
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5710 - accuracy: 0.7137
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5710 - accuracy: 0.7138
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5708 - accuracy: 0.7129
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5708 - accuracy: 0.7149
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5706 - accuracy: 0.7145
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5704 - accuracy: 0.7158
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5708 - accuracy: 0.7135
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5708 - accuracy: 0.7135
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5704 - accuracy: 0.7138
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5704 - accuracy: 0.7141
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5704 - accuracy: 0.7148
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5706 - accuracy: 0.7147
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5702 - accuracy: 0.7161
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5703 - accuracy: 0.7129
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5700 - accuracy: 0.7151
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5699 - accuracy: 0.7142
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5700 - accuracy: 0.7143
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5701 - accuracy: 0.7158
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5698 - accuracy: 0.7150
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5699 - accuracy: 0.7149
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5699 - accuracy: 0.7132
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7139
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5697 - accuracy: 0.7146
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5695 - accuracy: 0.7152
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7142
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5698 - accuracy: 0.7146
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7132
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7134
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5698 - accuracy: 0.7150
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5695 - accuracy: 0.7144
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5696 - accuracy: 0.7147
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7147
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7140
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5694 - accuracy: 0.7154
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5695 - accuracy: 0.7155
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7142
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5695 - accuracy: 0.7132
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5689 - accuracy: 0.7147
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5687 - accuracy: 0.7143
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5692 - accuracy: 0.7144
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5692 - accuracy: 0.7147
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5687 - accuracy: 0.7154
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5688 - accuracy: 0.7148
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5691 - accuracy: 0.7146
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5685 - accuracy: 0.7159
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7144
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5688 - accuracy: 0.7157
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5686 - accuracy: 0.7144
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7145
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5687 - accuracy: 0.7158
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5686 - accuracy: 0.7135
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5685 - accuracy: 0.7150
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5686 - accuracy: 0.7156
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5686 - accuracy: 0.7159
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7149
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5688 - accuracy: 0.7154
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5686 - accuracy: 0.7147
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5685 - accuracy: 0.7149
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7157
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5685 - accuracy: 0.7161
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5684 - accuracy: 0.7145
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7159
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5681 - accuracy: 0.7161
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7152
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5682 - accuracy: 0.7151
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7157
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5679 - accuracy: 0.7156
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5682 - accuracy: 0.7162
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5682 - accuracy: 0.7156

In [53]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5804 - accuracy: 0.7073 - 500ms/epoch - 2ms/step
Loss: 0.5804242491722107, Accuracy: 0.7072886228561401

In [56]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')